### ISSUE TITLE
installation docs

### ISSUE THREAD

**Issue by danielzzz** [discordianfish/docker-backup#3]
hi, is there any info on how to compile/install it? 
I am on ubuntu.

thanks, dan

**Comment by colthreepv** [comment]
releases would also be very useful.. so to download it right from github

**Comment by discordianfish** [comment]
I'm not really using this anymore but if someone wants to add a circleci config to build and upload release, I'm happy to merge this.

**Comment by colthreepv** [comment]
@discordianfish what are you using? what do you suggest?

**Comment by discordianfish** [comment]
Honestly? I rarely have to do backups :). This project is from when I was running things on bare metal. In a cloud environment where you have attachable volumes, you're probably better off using the cloud providers means of snapshotting/backing up the volumes.
That being said, if you don't have this doing it like docker-backup still makes sense I guess.. Unless there are volume backup features nowadays in Docker itself.
